# -*- coding: utf-8 -*-
"""Final DM_FAIZAH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mV2VkUrIkVZ20b_L8nNuQFcTZn43GB3Y

NAMA :
"""

#1 .Install & Import Library
!pip install catboost

import pandas as pd
import numpy as np
from catboost import CatBoostRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns

"""Kode diatas digunakan untuk menyiapkan proses analisis dan pemodelan data. Library Pandas dan NumPy digunakan untuk membaca dan mengolah data, sedangkan CatBoostRegressor digunakan sebagai model regresi berbasis Ordered Gradient Boosting. Fungsi train_test_split dipakai untuk membagi data menjadi data latih dan data uji, dan MAE, RMSE, serta R² digunakan untuk mengevaluasi kinerja model. Sementara itu, Matplotlib dan Seaborn digunakan untuk menampilkan hasil dalam bentuk grafik agar lebih mudah dipahami."""

# 2. Load Dataset
df = pd.read_csv("/content/drive/MyDrive/penjualan_tiket_pesawat.csv")
df.head()

# Informasi jumlah data
jumlah_record = df.shape[0]
jumlah_atribut = df.shape[1]

print("Jumlah record:", jumlah_record)
print("Jumlah atribut:", jumlah_atribut)

"""Output “Jumlah record: 500” menunjukkan bahwa dataset yang digunakan terdiri dari 500 baris data, dimana setiap baris merepresentasikan satu data transaksi penjualan tiket pesawat. Sementara itu, output “Jumlah atribut: 9” menunjukkan bahwa dataset memiliki 9 kolom atau variabel, yang berisi informasi terkait transaksi seperti data penumpang, maskapai, waktu, dan harga. Informasi ini digunakan untuk memberikan gambaran awal mengenai ukuran dan struktur dataset sebelum dilakukan proses pembersihan data dan pemodelan regresi."""

#3. DATA CLEANING (Pembersihan Data)
print("Ukuran data awal:", df.shape)

print("\nMissing value per kolom:")
print(df.isnull().sum())

print("\nJumlah data duplikat:", df.duplicated().sum())

df = df.drop_duplicates()

df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

print("\nMissing value setelah cleaning:")
print(df.isnull().sum())

print("\nUkuran data setelah cleaning:", df.shape)

df.to_csv("data_cleaned.csv", index=False)

"""Berdasarkan hasil pemeriksaan awal, dataset memiliki ukuran (500, 9) yang berarti terdiri dari 500 record dan 9 atribut. Hasil pengecekan missing value menunjukkan bahwa tidak terdapat nilai kosong pada seluruh kolom, sehingga data dinyatakan lengkap. Selain itu, hasil pemeriksaan data duplikat menunjukkan nilai 0, yang berarti tidak ditemukan data ganda dalam dataset. Setelah proses pembersihan data dilakukan, ukuran dataset tetap (500, 9), menandakan bahwa tidak ada data yang dihapus karena dataset sudah berada dalam kondisi bersih dan siap digunakan untuk tahap preprocessing dan pemodelan regresi."""

#4. Preprocessing + Feature Engineering
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day
df["Weekday"] = df["Date"].dt.weekday
df["Is_Weekend"] = df["Weekday"].apply(lambda x: 1 if x >= 5 else 0)

# Hapus kolom Date asli
df = df.drop(columns=["Date"])

# Simpan data hasil preprocessing
df.to_csv("data_preprocessed.csv", index=False)
df.head()

"""Pada tahap preprocessing, dilakukan feature engineering dengan mengekstraksi informasi dari atribut tanggal (Date) menjadi beberapa fitur baru, yaitu Year, Month, Day, Weekday, dan Is_Weekend. Fitur-fitur ini bertujuan untuk merepresentasikan informasi waktu transaksi secara lebih spesifik dan mudah dipahami oleh model regresi. Setelah proses ekstraksi selesai, kolom Date asli dihapus karena informasinya telah terwakili oleh fitur-fitur baru tersebut. Hasil preprocessing menunjukkan bahwa dataset kini memiliki atribut tambahan terkait waktu transaksi, sementara struktur data tetap rapi dan siap digunakan untuk tahap pemodelan."""

#5. Tentukan Fitur Kategorikal
cat_features = ["City", "Gender", "Airline", "Payment_Method"]

"""Pada tahap ini ditentukan fitur-fitur yang bersifat kategorikal, yaitu City, Gender, Airline, dan Payment_Method. Penentuan ini dilakukan agar model CatBoost Regressor dapat mengenali dan mengolah data kategori dengan benar tanpa perlu dilakukan encoding manual. Dengan mendefinisikan fitur kategorikal secara eksplisit, model dapat memanfaatkan karakteristik data kategori secara optimal dalam proses pemodelan regresi.

MODEL 1 — Prediksi TOTAL
"""

#6. Siapkan X & y
X_total = df.drop(columns=["Total"])
y_total = df["Total"]

"""Pada tahap ini, dataset dipisahkan menjadi variabel input (X) dan variabel target (y). Variabel X_total berisi seluruh fitur yang digunakan untuk melakukan prediksi, sedangkan variabel y_total berisi nilai Total yang menjadi target prediksi pada model regresi. Pemisahan ini dilakukan agar proses pelatihan model dapat fokus mempelajari hubungan antara fitur dan nilai target."""

#7. Train-Test Split (75% – 25%)
X_train, X_test, y_train, y_test = train_test_split(
    X_total, y_total, test_size=0.25, random_state=42
)

# Simpan split dataset
train_total = pd.concat([X_train, y_train], axis=1)
test_total = pd.concat([X_test, y_test], axis=1)

train_total.to_csv("train_total.csv", index=False)
test_total.to_csv("test_total.csv", index=False)

"""Pada tahap ini, data dibagi menjadi data latih (75%) dan data uji (25%). Data latih digunakan untuk melatih model regresi, sedangkan data uji digunakan untuk menguji kemampuan model dalam melakukan prediksi pada data yang belum pernah dilihat sebelumnya. Pembagian data ini bertujuan untuk mengevaluasi performa dan kemampuan generalisasi model. Hasil pembagian data kemudian disimpan dalam bentuk file CSV sebagai dokumentasi dan untuk memudahkan proses analisis lanjutan."""

#8. Train CatBoost Regressor
model_total = CatBoostRegressor(
    iterations=800,
    learning_rate=0.05,
    depth=8,
    loss_function='RMSE',
    verbose=0
)

model_total.fit(X_train, y_train, cat_features=cat_features)

"""Pada tahap ini dilakukan pelatihan model regresi menggunakan CatBoost Regressor dengan parameter yang telah ditentukan. Model dilatih menggunakan data latih untuk mempelajari pola dan hubungan antara fitur input dan nilai target. Penggunaan CatBoost Regressor memungkinkan model menangani fitur kategorikal secara langsung dan menghasilkan model regresi yang mampu melakukan prediksi secara akurat. Proses training ini menghasilkan model yang siap digunakan untuk tahap prediksi dan evaluasi."""

#9. Prediksi + Simpan Hasil Prediksi
y_pred_total = model_total.predict(X_test)

result_total = pd.DataFrame({
    "Actual_Total": y_test.values,
    "Predicted_Total": y_pred_total
})

result_total.to_csv("prediksi_total.csv", index=False)
result_total.head()

# VISUALISASI MODEL 1 (Scatter Plot))

# Scatter Plot Actual vs Predicted (TOTAL)
plt.figure(figsize=(6,6))
sns.scatterplot(x=y_test, y=y_pred_total)

plt.xlabel("Actual Total")
plt.ylabel("Predicted Total")
plt.title("Actual vs Predicted - Total")

plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()],
    'r--'
)

plt.savefig("scatter_total.png", dpi=300, bbox_inches="tight")
plt.show()

"""Pada bagian ini, model yang telah dilatih digunakan untuk melakukan prediksi terhadap data uji sehingga diperoleh nilai prediksi Total. Hasil prediksi kemudian digabungkan dengan nilai aktual ke dalam sebuah tabel yang berisi perbandingan antara nilai sebenarnya (Actual_Total) dan nilai hasil prediksi (Predicted_Total). Tabel ini disimpan dalam bentuk file CSV sebagai dokumentasi hasil prediksi dan bahan analisis lebih lanjut.


Berdasarkan grafik yang dihasilkan, terlihat bahwa sebagian besar titik data berada sangat dekat dengan garis ideal, yang menunjukkan bahwa hasil prediksi model sangat mendekati nilai aktual. Hal ini menandakan bahwa model CatBoost Regressor memiliki tingkat akurasi yang tinggi dalam memprediksi nilai Total. Penyebaran titik yang rapat dan mengikuti pola garis diagonal juga menunjukkan bahwa kesalahan prediksi relatif kecil dan model mampu menangkap pola hubungan data dengan baik.
"""

#10. Evaluasi + Simpan ke CSV
mae = mean_absolute_error(y_test, y_pred_total)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_total))
r2 = r2_score(y_test, y_pred_total)

eval_total = pd.DataFrame({
    "MAE": [mae],
    "RMSE": [rmse],
    "R2": [r2]
})

eval_total.to_csv("evaluasi_total.csv", index=False)
eval_total

"""Pada bagian ini dilakukan evaluasi kinerja model regresi dengan membandingkan nilai prediksi dengan nilai aktual pada data uji. Tiga metrik evaluasi yang digunakan adalah MAE (Mean Absolute Error), RMSE (Root Mean Squared Error), dan R² (Koefisien Determinasi). Nilai MAE mengukur rata-rata selisih absolut antara prediksi dan nilai sebenarnya, RMSE mengukur besarnya kesalahan dengan memberi penalti lebih besar pada kesalahan yang besar, sedangkan R² mengukur seberapa baik model menjelaskan variasi data. Hasil evaluasi kemudian disimpan dalam bentuk file CSV untuk dokumentasi.


Berdasarkan hasil evaluasi yang diperoleh, nilai MAE sebesar 68.239 menunjukkan bahwa rata-rata kesalahan prediksi model sekitar 68 ribu satuan dari nilai Total. Nilai RMSE sebesar 93.470 menunjukkan bahwa kesalahan besar masih relatif kecil dan terkendali. Sementara itu, nilai R² sebesar 0,9985 menandakan bahwa model mampu menjelaskan sekitar 99,85% variasi data, yang menunjukkan bahwa performa model sangat baik dan akurat dalam melakukan prediksi nilai Total.
"""

#11. Feature Importance TOTAL
importances = model_total.get_feature_importance()
features = X_total.columns

fi_total = pd.DataFrame({
    "Feature": features,
    "Importance": importances
})

fi_total.to_csv("feature_importance_total.csv", index=False)
fi_total


# Bar Plot
importances = model_total.get_feature_importance()
features = X_total.columns

plt.figure(figsize=(8,6))
sns.barplot(x=importances, y=features)

plt.title("Feature Importance - Total")

plt.savefig("feature_importance_total.png", dpi=300, bbox_inches="tight")
plt.show()

"""Pada tahap ini dilakukan analisis feature importance untuk mengetahui seberapa besar kontribusi masing-masing fitur dalam memprediksi nilai Total. Fungsi get_feature_importance() digunakan untuk mengambil nilai kepentingan setiap fitur dari model CatBoost yang telah dilatih. Nilai importance tersebut kemudian dipasangkan dengan nama fitur dan disimpan dalam bentuk tabel serta file CSV sebagai dokumentasi hasil analisis.


Berdasarkan grafik feature importance, terlihat bahwa Ticket_Quantity merupakan fitur yang paling berpengaruh terhadap nilai Total, diikuti oleh Ticket_Price. Hal ini menunjukkan bahwa jumlah tiket yang dibeli dan harga tiket menjadi faktor utama dalam menentukan total transaksi. Sementara itu, fitur lain seperti City, Gender, Airline, Payment_Method, serta fitur waktu memiliki pengaruh yang relatif kecil terhadap nilai Total. Hasil ini sesuai dengan logika bisnis, karena nilai Total secara langsung dipengaruhi oleh jumlah tiket dan harga tiket.

MODEL 2 — Prediksi TICKET PRICE
"""

#12. Siapkan X & y
X_price = df.drop(columns=["Ticket_Price"])
y_price = df["Ticket_Price"]

"""Pada tahap ini, dataset kembali dipisahkan menjadi variabel input (X) dan variabel target (y) untuk tujuan prediksi harga tiket (Ticket_Price). Variabel X_price berisi seluruh fitur yang digunakan sebagai input model, sedangkan y_price berisi nilai Ticket_Price yang menjadi target prediksi. Pemisahan ini dilakukan agar model regresi dapat mempelajari hubungan antara fitur-fitur yang tersedia dengan harga tiket secara efektif."""

#13. Train-Test Split (75% – 25%)
X_train2, X_test2, y_train2, y_test2 = train_test_split(
    X_price, y_price, test_size=0.25, random_state=42
)

train_price = pd.concat([X_train2, y_train2], axis=1)
test_price = pd.concat([X_test2, y_test2], axis=1)

train_price.to_csv("train_price.csv", index=False)
test_price.to_csv("test_price.csv", index=False)

"""Pada tahap ini, data dibagi menjadi data latih (75%) dan data uji (25%) untuk tujuan prediksi harga tiket (Ticket_Price). Data latih digunakan untuk melatih model agar dapat mempelajari pola hubungan antara fitur dan harga tiket, sedangkan data uji digunakan untuk mengevaluasi kinerja model pada data yang belum pernah dilihat sebelumnya. Hasil pembagian data kemudian disimpan dalam bentuk file CSV untuk memudahkan dokumentasi dan analisis lanjutan."""

#14. Train CatBoost
model_price = CatBoostRegressor(
    iterations=800,
    learning_rate=0.05,
    depth=8,
    loss_function='RMSE',
    verbose=0
)

model_price.fit(X_train2, y_train2, cat_features=cat_features)

"""Pada tahap ini dilakukan pelatihan model CatBoost Regressor untuk memprediksi Ticket_Price menggunakan data latih yang telah disiapkan. Model dilatih agar dapat mempelajari hubungan antara fitur input dan harga tiket, dengan memanfaatkan kemampuan CatBoost dalam menangani fitur kategorikal secara langsung. Hasil dari proses training ini adalah model regresi yang siap digunakan untuk melakukan prediksi harga tiket pada data uji serta dievaluasi kinerjanya."""

#15. Prediksi + Simpan ke CSV
y_pred_price = model_price.predict(X_test2)

result_price = pd.DataFrame({
    "Actual_Price": y_test2.values,
    "Predicted_Price": y_pred_price
})

result_price.to_csv("prediksi_price.csv", index=False)
result_price.head()


# Scatter Plot Actual vs Predicted (TICKET PRICE)
plt.figure(figsize=(6,6))
sns.scatterplot(x=y_test2, y=y_pred_price)

plt.xlabel("Actual Ticket Price")
plt.ylabel("Predicted Ticket Price")
plt.title("Actual vs Predicted - Ticket Price")

plt.plot(
    [y_test2.min(), y_test2.max()],
    [y_test2.min(), y_test2.max()],
    'r--'
)

plt.savefig("scatter_ticket_price.png", dpi=300, bbox_inches="tight")
plt.show()

"""Pada tahap ini, model CatBoost yang telah dilatih digunakan untuk melakukan prediksi harga tiket (Ticket_Price) pada data uji. Nilai hasil prediksi kemudian digabungkan dengan nilai aktual ke dalam sebuah tabel yang berisi perbandingan antara harga tiket sebenarnya dan harga tiket hasil prediksi. Tabel tersebut disimpan dalam bentuk file CSV sebagai dokumentasi hasil prediksi dan bahan analisis lanjutan.


Visualisasi yang digunakan adalah scatter plot yang membandingkan nilai aktual Ticket_Price (sumbu X) dengan nilai prediksi Ticket_Price (sumbu Y). Garis putus-putus merah merupakan garis ideal (y = x) yang menunjukkan kondisi ketika nilai prediksi sama dengan nilai aktual.


Berdasarkan grafik yang dihasilkan, terlihat bahwa titik-titik data tersebar sangat dekat dengan garis ideal, yang menunjukkan bahwa hasil prediksi model sangat mendekati nilai aktual. Hal ini menandakan bahwa model CatBoost Regressor memiliki kemampuan yang baik dan stabil dalam memprediksi harga tiket. Penyimpangan titik yang kecil dari garis diagonal menunjukkan bahwa kesalahan prediksi relatif rendah.
"""

#15. Evaluasi + Simpan CSV
mae2 = mean_absolute_error(y_test2, y_pred_price)
rmse2 = np.sqrt(mean_squared_error(y_test2, y_pred_price))
r22 = r2_score(y_test2, y_pred_price)

eval_price = pd.DataFrame({
    "MAE": [mae2],
    "RMSE": [rmse2],
    "R2": [r22]
})

eval_price.to_csv("evaluasi_price.csv", index=False)
eval_price

"""Pada tahap ini dilakukan evaluasi kinerja model regresi untuk prediksi Ticket_Price dengan membandingkan nilai prediksi dan nilai aktual pada data uji. Tiga metrik evaluasi yang digunakan adalah MAE, RMSE, dan R². Hasil evaluasi disusun dalam bentuk tabel dan disimpan ke dalam file CSV sebagai dokumentasi dan bahan analisis performa model.


Berdasarkan hasil evaluasi, nilai MAE sebesar 30.720 menunjukkan bahwa rata-rata kesalahan prediksi harga tiket sekitar 30 ribu satuan dari nilai sebenarnya. Nilai RMSE sebesar 39.012 menunjukkan bahwa kesalahan prediksi relatif kecil dan tidak banyak dipengaruhi oleh error yang besar. Sementara itu, nilai R² sebesar 0,9917 menunjukkan bahwa model mampu menjelaskan sekitar 99,17% variasi data harga tiket, yang menandakan bahwa performa model sangat baik dan stabil.
"""

#16. Feature Importance + Simpan CSV
importances2 = model_price.get_feature_importance()
features2 = X_price.columns

fi_price = pd.DataFrame({
    "Feature": features2,
    "Importance": importances2
})

fi_price.to_csv("feature_importance_price.csv", index=False)
fi_price


# Bar Plot Feature Importance (TICKET PRICE)
plt.figure(figsize=(8,6))
sns.barplot(x=importances2, y=X_price.columns)

plt.title("Feature Importance - Ticket Price")

plt.savefig("feature_importance_ticket_price.png", dpi=300, bbox_inches="tight")
plt.show()

"""Pada tahap ini dilakukan analisis feature importance untuk mengetahui kontribusi masing-masing fitur dalam memprediksi Ticket_Price. Nilai kepentingan setiap fitur diperoleh dari model CatBoost Regressor yang telah dilatih, kemudian disusun dalam bentuk tabel dan disimpan ke dalam file CSV sebagai dokumentasi. Selain itu, hasil feature importance divisualisasikan menggunakan bar chart untuk memudahkan interpretasi.


Berdasarkan grafik feature importance, terlihat bahwa Total merupakan fitur yang paling berpengaruh dalam memprediksi harga tiket, diikuti oleh Ticket_Quantity. Hal ini menunjukkan bahwa harga tiket sangat dipengaruhi oleh nilai total transaksi dan jumlah tiket yang dibeli. Sementara itu, fitur lain seperti City, Gender, Airline, Payment_Method, serta fitur waktu memiliki pengaruh yang relatif kecil terhadap prediksi Ticket_Price.
"""